FROM postgres:15

RUN apt-get update && apt-get install -y cron && rm -rf /var/lib/apt/lists/*

COPY backup.sh /backup.sh
COPY crontab.txt /crontab.txt

# ✅ limpiar CRLF y BOM
RUN sed -i 's/\r$//' /backup.sh /crontab.txt \
    && sed -i '1s/^\xEF\xBB\xBF//' /crontab.txt \
    && chmod +x /backup.sh \
    && crontab /crontab.txt

CMD ["cron", "-f"]
